.PHONY: build clean rebuild

# Variables && Constants:
# _valid_identifier = valid_value
PROJECT_NAME = myproj

# Sections:

build:
	@echo "\033[1;2;3;4;5;32mCalled\033[0m \"build\""
# TODO: Call the build-system program that you still need to write/develop/implement
	@echo "\033[1;2;3;4;5;33mDone Building!\033[0m"

clean:
	@echo "\033[1;2;3;4;5;32mCalled\033[0m \"clean\""
	rm -v ./build/binaries*.exe ./build/objects/*.o
	@echo "\033[1;2;3;4;5;33mDone Cleaning!\033[0m"

rebuild: clean build

# Other:
# ...
